### ISSUE TITLE
Add markers to map

### ISSUE THREAD

**Issue by Moomox** [deepstreamIO/deepstream.io-client-java#116]
Friends, has anyone an idea why the marker method crashes ??????

List recordList = client.record.getList("driver/users");

Log.d("Deepstream", Arrays.toString(recordList.getEntries()));

for (String recordName : recordList.getEntries())
{

    Record record = client.record.getRecord(recordName);

    record.subscribe(new RecordChangedCallback()
    {

        @Override
        public void onRecordChanged(String recordName, JsonElement data)
        {

                    Gson gson = new Gson();

                    JsonObject jsonData = (JsonObject) gson.toJsonTree(data);

                    double latitude   = jsonData.get("lat").getAsDouble();

                    double longitude  = jsonData.get("lng").getAsDouble();

                    Marker marker = map.addMarker(new MarkerOptions()
                    .position(new LatLng(latitude, longitude))
                    .title("San Francisco")
                    .snippet("Population: 776733"));

                    System.out.println(String.format("Record '%s' changed, data is now: %s", recordName, data));

        }

    });

}

Process: com.app, PID: 17957
com.google.maps.api.android.lib6.common.apiexception.c: Not on the main thread
at com.google.maps.api.android.lib6.common.k.b(:com.google.android.gms.DynamiteModulesB@11518448:11)
at com.google.maps.api.android.lib6.common.p.a(:com.google.android.gms.DynamiteModulesB@11518448:5)
at com.google.maps.api.android.lib6.impl.ba.a(:com.google.android.gms.DynamiteModulesB@11518448:483)
at com.google.android.gms.maps.internal.k.onTransact(:com.google.android.gms.DynamiteModulesB@11518448:94)
at android.os.Binder.transact(Binder.java:499)
at com.google.android.gms.internal.zzeb.zza(Unknown Source)
at com.google.android.gms.maps.internal.zzg.addMarker(Unknown Source)
at com.google.android.gms.maps.GoogleMap.addMarker(Unknown Source)
at com.appMapActivity.updatePoll(MapActivity.java:408)
at com.app.MapActivity.access$200(MapActivity.java:63)
at com.app.MapActivity$7.onRecordChanged(MapActivity.java:324)
at io.deepstream.Record.completeChange(Record.java:708)
at io.deepstream.Record.applyUpdate(Record.java:619)
at io.deepstream.Record.onMessage(Record.java:527)
at io.deepstream.RecordHandler.handle(RecordHandler.java:476)
at io.deepstream.Connection$4.run(Connection.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:776)

**Comment by AlexBHarley** [comment]
Android has a thread for the UI and you need to submit things to run on it, otherwise you run into `Not on the main thread` errors. There is some more info about it here https://stackoverflow.com/questions/39331723/java-lang-illegalstateexception-not-on-the-main-thread-google-maps
