### ISSUE TITLE
MESSAGE_PARSE_ERROR: UNKNOWN_TYPE (U)

### ISSUE THREAD

**Issue by chinmaygit** [deepstreamIO/deepstream.io-client-java#44]
chinmay [6:55 PM]  
FATAL EXCEPTION: Timer-0Process: com.vikilabs.hombot.app, PID: 6756
                                                                      io.deepstream.DeepstreamException: CONNECTION_ERROR: MESSAGE_PARSE_ERROR: UNKNOWN_TYPE (U)
                                                                          at io.deepstream.DeepstreamClientAbstract.onError(DeepstreamClientAbstract.java:56)
                                                                          at io.deepstream.Connection$1.run(Connection.java:180)
                                                                          at java.util.Timer$TimerImpl.run(Timer.java:284)
E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()

**Comment by yasserf** [comment]
Hey, there was a PR that was just raised for this against the website. Its because java doesn't have a concept of undefined. We'll fix this tomorrow.

**Comment by chinmaygit** [comment]
Sure. thank you..
