### ISSUE TITLE
Unsubscribe throw NPE

### ISSUE THREAD

**Issue by yan5** [deepstreamIO/deepstream.io-client-java#61]
I'm running into the following error 
```
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.deepstream.Endpoint.send(java.lang.String)' on a null object reference
                                                                   at io.deepstream.Connection.send(Connection.java:114)
                                                                   at io.deepstream.EventHandler.unsubscribe(EventHandler.java:68)

```
when I'm trying to `unsubscribe` in `onDestroy()` as                 
`deepstreamClient.event.unsubscribe(channel, mChatEventListener);`

the `deepstreamClient` was initialized as `deepstreamClient = new DeepstreamClient(url);`

Any idea?

**Comment by yasserf** [comment]
It appears the connection was lost and hence your trying to send something on a closed state.

What hook is 'onDestroy' exactly?

**Comment by yan5** [comment]
onDestroy() on Activity.

I was trying to close/unsubscribe to avoid any memory leak, coz these EvenListeners are anonymous inner classes.
Is there any other cleaner way to remove them?

I guess it would great if we could add api's for 
- removing those listeners (all listener or by channel name)
- removing ConnectionChangeListeners and RuntimeErrorHandlers

which can be used while closing or destroying the activity to avoid memory leaks.

**Comment by yasserf** [comment]
Are you creating a new connection per activity?

**Comment by yan5** [comment]
Yes. Coz activities are independent in nature in my case. Do you suggest any alternatives?
in either case it would be great if we could get clean api to tear down and clean up.
