### ISSUE TITLE
Crash on Connection Drop

### ISSUE THREAD

**Issue by aschober** [deepstreamIO/deepstream.io-client-java#85]
We're seeing the below Fatal Exception occur in the Deepstream library consistently when have valid OPEN connection after login via WiFi and then WiFi connectivity drops on our device.

Using deepstream.io-client-java v2.0.7.

```
04-20 13:38:02.870 6357-20138/com.testapp.debug E/AndroidRuntime: FATAL EXCEPTION: Timer-0
                                                                                 Process: com.testapp.debug, PID: 6357
                                                                                 io.deepstream.DeepstreamException: CONNECTION_ERROR: null
                                                                                     at io.deepstream.DeepstreamClientAbstract.onError(DeepstreamClientAbstract.java:59)
                                                                                     at io.deepstream.Connection$1.run(Connection.java:194)
                                                                                     at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by AlexBHarley** [comment]
@aschober, this is expected in the sense that the connection has died, so there is a `CONNECTION_ERROR `. If you don't want this to throw an exception you can put a listener on the error event with `client.setRuntimeErrorHandler `. Admittedly the reason could be better than `null`. The current approach is either one of two things, 

- infinite reconnect attempts
- store some local state and restart the session when internet connectivity comes back.

We're hoping to tackle some better offline first functionality with resuming sessions and the like, in the near future.

**Comment by sanketmthakare** [comment]
seeing the above same Fatal Exception occur in the Deepstream library consistently when server is down. even setRuntimeErrorHandler can not handle exception on first time login when server is down.

**Comment by irfaan008** [comment]
I have put my deepstream client code inside try block but still it doesn't go to catch block on connection exception (when internet is not available)

**Comment by sanketmthakare** [comment]
Hello irfaan try block will not catch the exception on internet is not available. You have to implement setruntimeerrorhandle in your class to check catch exception at run time.

**Comment by jamesalexscott** [comment]
You can extend DeepStreamClient and add a constructor that allows you to pass in set DeepstreamRuntimeErrorHandler. This worked for me with the first time login when server is down
